name: Terraform Deployment

on:
  push:
    branches:
      - main  # This will trigger the workflow on pushing to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.0  # Specify the Terraform version you need

    - name: aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-2
        aws-access-key-id: AKIAZ7SAKV6CNN5B5O5T
        aws-secret-access-key: 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
       

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
